---
- hosts: proxy
  tasks:
  - name: insert/update squid.conf whitelist
    register: squid_update
    blockinfile:
      path: /etc/squid/squid.conf
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
      content: |
        #
        #Handling HTTP requests
        http_port 3129 intercept
        acl allowed_http_sites dstdomain .amazonaws.com
        #acl allowed_http_sites dstdomain [you can add other domains to permit]
        http_access allow allowed_http_sites

        #Handling HTTPS requests
        https_port 3130 cert=/etc/squid/ssl/squid.pem ssl-bump intercept
        acl SSL_port port 443
        http_access allow SSL_port
        acl allowed_https_sites ssl::server_name .amazonaws.com
        #acl allowed_https_sites ssl::server_name [you can add other domains to permit]
        #
      backup: yes 
  - name: reload squid
    shell: service squid reload
    when: squid_update.changed
    
